# Generated by Django 5.0.6 on 2024-05-31 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Destructoras', 'Destructoras de Documento'), ('Contadoras', 'Contadoras de billetes'), ('Calculadoras', 'Calculadoras'), ('Accesorios para Moviles', 'Accesorios para Moviles'), ('Proyectores Android', 'Proyectores Android')], max_length=60, verbose_name='Categoría')),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Subcategoría')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='web.categoria')),
            ],
            options={
                'verbose_name_plural': 'Subcategorías',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del modelo')),
                ('especificaciones', models.TextField(verbose_name='Especificaciones y descripción del modelo')),
                ('manual', models.URLField(verbose_name='URL del manual en formato pdf')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='web.subcategoria')),
            ],
            options={
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.CreateModel(
            name='SubCategoriaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.modelo')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.subcategoria')),
            ],
            options={
                'unique_together': {('subcategoria', 'modelo')},
            },
        ),
    ]
