# Generated by Django 5.0.6 on 2024-10-08 20:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Destructoras', 'Destructoras de Documento'), ('Contadoras', 'Contadoras de billetes'), ('Calculadoras', 'Calculadoras'), ('Accesorios para Moviles', 'Accesorios para Moviles'), ('Proyectores', 'Proyectores')], max_length=60, verbose_name='Categoría')),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='CondicionIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Consumidor Final', 'Consumidor Final'), ('inscripto', 'Inscripto'), ('monotributista', 'Monotributista'), ('exento', 'Exento')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del modelo')),
                ('especificaciones', models.TextField(verbose_name='Especificaciones y descripción del modelo')),
                ('manual', models.URLField(verbose_name='URL del manual en formato pdf')),
            ],
            options={
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('distribuidor', 'Distribuidor'), ('proveedor', 'Proveedor'), ('particular', 'Particular')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre o razon social')),
                ('empresa', models.BooleanField(default=False)),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True, verbose_name='Razon Social')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre y apellido del contacto')),
                ('cuit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cuit')),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio')),
                ('localidad', models.CharField(blank=True, max_length=45, null=True, verbose_name='Localidad')),
                ('codigo_postal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo Postal')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono Alternativo')),
                ('email', models.CharField(max_length=100, null=True, unique=True, verbose_name='Email')),
                ('condicion_iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.condicioniva', verbose_name='Condición IVA')),
                ('provincia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.provincia')),
                ('tipo_cliente', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='web.tipocliente', verbose_name='Tipo Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=100)),
                ('garantia', models.BooleanField(default=False)),
                ('accesorios', models.ManyToManyField(related_name='maquinas', to='web.accesorio')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.categoria')),
                ('falla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.falla')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ingresada', 'Ingresada'), ('presupuestada', 'Presupuestada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('reparada', 'Reparada'), ('entregada', 'Entregada')], default='ingresada', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(default='---', verbose_name='notas con respecto a la maquina')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cliente')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ingresada', 'Ingresada'), ('presupuestada', 'Presupuestada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('reparada', 'Reparada'), ('entregada', 'Entregada')], max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ordendereparacion')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('rechazado', models.BooleanField(default=False)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_rechazo', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(default='---', verbose_name='Descripcion del presupuesto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='web.ordendereparacion')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Subcategoría')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='web.categoria')),
            ],
            options={
                'verbose_name_plural': 'Subcategorías',
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.categoria')),
                ('subcategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.subcategoria')),
            ],
        ),
        migrations.AddField(
            model_name='modelo',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='web.subcategoria'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='subcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.subcategoria'),
        ),
        migrations.CreateModel(
            name='SubCategoriaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.modelo')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.subcategoria')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subcategoriamodelo',
            constraint=models.UniqueConstraint(fields=('subcategoria', 'modelo'), name='unique_subcategoria_modelo'),
        ),
    ]
