# Generated by Django 5.0.6 on 2024-10-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('distribuidor', 'Distribuidor'), ('proveedor', 'Proveedor'), ('particular', 'Particular')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='cuit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cuit'),
        ),
        migrations.AlterField(
            model_name='condicioniva',
            name='nombre',
            field=models.CharField(choices=[('Consumidor Final', 'Consumidor Final'), ('inscripto', 'Inscripto'), ('monotributista', 'Monotributista'), ('exento', 'Exento')], max_length=20, unique=True),
        ),
    ]
