# Generated by Django 5.0.6 on 2024-06-05 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('particular', 'Particular'), ('inscripto', 'Inscripto'), ('monotributista', 'Monotributista'), ('exento', 'Exento')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido del cliente')),
                ('empresa', models.BooleanField(default=False)),
                ('razon_social', models.CharField(max_length=100, null=True, verbose_name='Razon Social')),
                ('domicilio', models.CharField(max_length=200, verbose_name='Domicilio')),
                ('localidad', models.CharField(max_length=45, verbose_name='Localidad')),
                ('codigo_postal', models.CharField(max_length=6, verbose_name='Codigo Postal')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Email')),
                ('condicion_iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.condicioniva', verbose_name='Condición IVA')),
            ],
        ),
    ]
