# Generated by Django 5.0.6 on 2024-11-04 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_cliente_dni_cliente_migrated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=60, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='condicion_iva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.condicioniva', verbose_name='Condicion IVA'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre o razon socia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Razon social'),
        ),
    ]
