# Generated by Django 5.0.6 on 2024-10-05 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_tipocliente_cliente_cuit_alter_condicioniva_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='web.tipocliente', verbose_name='Tipo Cliente'),
        ),
    ]
