# Generated by Django 5.0.6 on 2024-06-07 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_condicioniva_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('garantia', models.BooleanField(default=False)),
                ('accesorios', models.ManyToManyField(related_name='maquinas', to='web.accesorio')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.categoria')),
                ('falla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.falla')),
                ('subcategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ingresada', 'Ingresada'), ('presupuestada', 'Presupuestada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('reparada', 'Reparada'), ('entregada', 'Entregada')], default='ingresada', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cliente')),
                ('falla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.falla')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ingresada', 'Ingresada'), ('presupuestada', 'Presupuestada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('reparada', 'Reparada'), ('entregada', 'Entregada')], max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ordendereparacion')),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.categoria')),
                ('subcategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='web.ordendereparacion')),
                ('repuestos', models.ManyToManyField(related_name='presupuestos', to='web.repuesto')),
            ],
        ),
    ]
