# Generated by Django 5.0.6 on 2024-06-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_accesorio_falla_maquina_ordendereparacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Razon Social'),
        ),
    ]
