# Generated by Django 5.0.6 on 2024-11-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_modelo_especificaciones_alter_modelo_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='falla',
        ),
        migrations.DeleteModel(
            name='Falla',
        ),
    ]
