# Generated by Django 5.0.6 on 2024-06-09 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_cliente_razon_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendereparacion',
            name='falla',
        ),
    ]
