# Generated by Django 5.0.6 on 2024-11-05 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_maquina_falla_delete_falla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='total',
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='nota_interna',
            field=models.TextField(blank=True, null=True, verbose_name='Nota interna para técnicos'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='total_estimado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='cantidad_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='codigo',
            field=models.CharField(default='SIN-CODIGO', max_length=50),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='costo_ultima_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='costo_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='stock_critico',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='accesorios',
            field=models.ManyToManyField(blank=True, related_name='maquinas', to='web.accesorio'),
        ),
        migrations.CreateModel(
            name='MovimientoStockRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('destino', models.CharField(blank=True, help_text="Número de Orden o 'Mostrador' para ventas directas", max_length=100, null=True)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.repuesto')),
            ],
        ),
        migrations.AddField(
            model_name='repuesto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.proveedor'),
        ),
        migrations.CreateModel(
            name='RepuestoPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.presupuesto')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.repuesto')),
            ],
        ),
    ]
