# Generated by Django 5.0.6 on 2024-06-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_ordendereparacion_falla'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendereparacion',
            name='notas',
            field=models.TextField(default='---', verbose_name='notas con respecto a la maquina'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='descripcion',
            field=models.TextField(default='---', verbose_name='Descripcion del presupuesto'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='rechazado',
            field=models.BooleanField(default=False),
        ),
    ]
