# Generated by Django 5.0.6 on 2024-06-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_ordendereparacion_notas_presupuesto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('Destructoras', 'Destructoras de Documento'), ('Contadoras', 'Contadoras de billetes'), ('Calculadoras', 'Calculadoras'), ('Accesorios para Moviles', 'Accesorios para Moviles'), ('Proyectores', 'Proyectores')], max_length=60, verbose_name='Categoría'),
        ),
    ]
