# Generated by Django 5.0.6 on 2024-11-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_proveedor_remove_presupuesto_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='repuestos',
            field=models.ManyToManyField(through='web.RepuestoPresupuesto', to='web.repuesto'),
        ),
    ]
