# Generated by Django 5.0.6 on 2024-11-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_presupuesto_repuestos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='subcategoria',
        ),
    ]
