# Generated by Django 5.0.6 on 2024-06-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='repuestos',
            field=models.ManyToManyField(blank=True, related_name='presupuestos', to='web.repuesto'),
        ),
    ]
