# Generated by Django 5.0.6 on 2024-06-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_accesorio_categoria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategoriamodelo',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='subcategoriamodelo',
            constraint=models.UniqueConstraint(fields=('subcategoria', 'modelo'), name='unique_subcategoria_modelo'),
        ),
    ]
