# Generated by Django 5.0.6 on 2024-11-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_repuesto_proveedor_alter_proveedor_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, default='--', max_length=200),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, default='--', max_length=254),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, default='--', max_length=20),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='ubicacion',
            field=models.CharField(blank=True, default='---', max_length=100),
        ),
    ]
