# Generated by Django 4.2.16 on 2025-01-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_proveedor_direccion_alter_proveedor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostockrepuesto',
            name='costo_promedio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo promedio al momento del movimiento', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='movimientostockrepuesto',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo por unidad para entradas', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='correo_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
