# Generated by Django 5.0.6 on 2024-06-24 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_subcategoriamodelo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.categoria'),
        ),
    ]
