# Generated by Django 5.0.6 on 2024-06-24 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_accesorio_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.modelo'),
        ),
    ]
