# Generated by Django 4.2.16 on 2025-01-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_movimientostockrepuesto_costo_promedio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repuesto',
            old_name='cantidad_actual',
            new_name='stock',
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
    ]
