# Generated by Django 5.0.6 on 2024-06-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_maquina_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='repuestos',
        ),
    ]
