# Generated by Django 4.2.16 on 2025-01-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_rename_cantidad_actual_repuesto_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostockrepuesto',
            name='stock_parcial',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
