# Generated by Django 5.0.6 on 2024-06-27 18:00


from django.db import migrations, models
import uuid

def generate_uuids(apps, schema_editor):
    Presupuesto = apps.get_model('web', 'Presupuesto')
    for presupuesto in Presupuesto.objects.all():
        presupuesto.uuid = uuid.uuid4()
        presupuesto.save()

class Migration(migrations.Migration):


    dependencies = [
        ('web', '0013_remove_presupuesto_repuestos'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(generate_uuids),
        migrations.AlterField(
            model_name='presupuesto',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]

 