# Generated by Django 5.0.6 on 2024-07-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_presupuesto_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono_alternativo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono Alternativo'),
        ),
    ]
